spring:
  profiles:
    include: devRedisson
  #排除 原生Druid的快速配置类
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: admin1
    primary: master #设置默认的数据源或者数据源组,默认值即为master
    dynamic:
      p6spy: true # 默认false,建议线上关闭,打印完整sql
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #validation-query: SELECT 1 FROM DUAL
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://123.56.175.54:3306/flowable?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 1qaz2wsx#
          #password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          #druid: #以下参数针对每个库可以重新设置druid参数
        #slave: #多数据源可开启
        #  url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        #  username: root
        #  password: root
        #  driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: false
  redis:
    database: 0
    port: 6379
    host: 123.56.175.54
    password: #pox
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示无限制)
        max-wait: -1
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
      #sentinel:
      #master: mymaster
      #nodes: 168.168.168.101:26379,168.168.168.102:26379,168.168.168.103:26379
debug: true
swagger-enable: true #生产可关闭设置成false
#打印mybatis-plussql，生产应关闭
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl